# Site settings
title: camelCase
description: >
  thoughts on code

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://obedm503.github.io" # the base hostname & protocol for your site

author: obedm503

authorInfo:
  picture: /assets/media/avatar.png
  fullname: obedm503
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: obedm503
  # twitter: electrik_frog
  disqus: obedm503-camelcase

# google_analytics: 'UA-XXXXXXXX-X'

# permalinks
collections:
  posts:
    permalink: /:year-:month-:day-:title.html
  pages:
    permalink: /:title.html
  categories:
    output: true
    permalink: /:name.html


# Syntax highlighting
highlightstyle: 'atelier-lakeside.dark'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown

gems:
  - jekyll-feed

#prose config
prose:
  siteurl: "https://obedm503.github.io/"
  rooturl: ""
  media: "assets/media"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          value:""
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Summary/Excerpt"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Categories"
          options:
            - name: "projects"
              value: "projects"
            - name: "frontEnd"
              value: "frontEnd"
            - name: "hydrid"
              value: "hybrid"
            - name: "spareTime"
              value: "spareTime"
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
